# Generated by Django 5.2.1 on 2025-05-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
