# Generated by Django 5.2.1 on 2025-05-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_desert_menu_hot_menu_rename_menu_cold_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cold_menu',
            name='medium_price',
        ),
        migrations.RemoveField(
            model_name='hot_menu',
            name='medium_price',
        ),
        migrations.AlterField(
            model_name='cold_menu',
            name='large_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_menu',
            name='small_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desert_menu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hot_menu',
            name='large_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hot_menu',
            name='small_price',
            field=models.IntegerField(),
        ),
    ]
