# Generated by Django 5.2.1 on 2025-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='add_url',
            field=models.URLField(default='https://www.google.com/maps'),
        ),
    ]
